# Generated by Django 6.0.4 on 2026-04-22 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='নাম / প্রতিষ্ঠান')),
                ('phone', models.CharField(max_length=20, verbose_name='মোবাইল')),
                ('email', models.EmailField(max_length=254, verbose_name='ইমেইল')),
                ('ad_type', models.CharField(choices=[('হোমপেজ ব্যানার', 'হোমপেজ ব্যানার'), ('ইনলাইন বিজ্ঞাপন', 'ইনলাইন বিজ্ঞাপন'), ('বিজ্ঞপ্তি / প্রেস রিলিজ', 'বিজ্ঞপ্তি / প্রেস রিলিজ'), ('স্পনসর কন্টেন্ট', 'স্পনসর কন্টেন্ট'), ('সোশ্যাল মিডিয়া বুস্ট', 'সোশ্যাল মিডিয়া বুস্ট'), ('অন্যান্য', 'অন্যান্য')], max_length=60, verbose_name='বিজ্ঞাপনের ধরন')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='বাজেট (টাকা)')),
                ('duration', models.CharField(blank=True, choices=[('১ সপ্তাহ', '১ সপ্তাহ'), ('১ মাস', '১ মাস'), ('৩ মাস', '৩ মাস'), ('৬ মাস', '৬ মাস'), ('১ বছর', '১ বছর')], max_length=20, verbose_name='মেয়াদ')),
                ('details', models.TextField(verbose_name='বিবরণ')),
                ('status', models.CharField(choices=[('pending', 'মুলতুবি'), ('contacted', 'যোগাযোগ হয়েছে'), ('confirmed', 'নিশ্চিত'), ('rejected', 'বাতিল')], default='pending', max_length=20, verbose_name='অবস্থা')),
                ('notes', models.TextField(blank=True, verbose_name='অভ্যন্তরীণ নোট')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='তারিখ')),
            ],
            options={
                'verbose_name': 'বিজ্ঞাপন আবেদন',
                'verbose_name_plural': 'বিজ্ঞাপন আবেদনসমূহ',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='নাম')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='মোবাইল')),
                ('email', models.EmailField(max_length=254, verbose_name='ইমেইল')),
                ('subject', models.CharField(choices=[('সংবাদ পাঠান', 'সংবাদ পাঠান'), ('মতামত / মন্তব্য', 'মতামত / মন্তব্য'), ('তথ্য সংশোধন', 'তথ্য সংশোধন'), ('বিজ্ঞাপন সংক্রান্ত', 'বিজ্ঞাপন সংক্রান্ত'), ('অভিযোগ', 'অভিযোগ'), ('অন্যান্য', 'অন্যান্য')], max_length=60, verbose_name='বিষয়')),
                ('message', models.TextField(verbose_name='বার্তা')),
                ('is_read', models.BooleanField(default=False, verbose_name='পড়া হয়েছে')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='তারিখ')),
            ],
            options={
                'verbose_name': 'যোগাযোগ বার্তা',
                'verbose_name_plural': 'যোগাযোগ বার্তাসমূহ',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RepresentativeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='পূর্ণ নাম')),
                ('phone', models.CharField(max_length=20, verbose_name='মোবাইল')),
                ('email', models.EmailField(max_length=254, verbose_name='ইমেইল')),
                ('role', models.CharField(choices=[('জেলা প্রতিনিধি', 'জেলা প্রতিনিধি'), ('উপজেলা প্রতিনিধি', 'উপজেলা প্রতিনিধি'), ('স্টাফ রিপোর্টার', 'স্টাফ রিপোর্টার'), ('ফটো সাংবাদিক', 'ফটো সাংবাদিক'), ('ভিডিও জার্নালিস্ট', 'ভিডিও জার্নালিস্ট'), ('অনুসন্ধানী সাংবাদিক', 'অনুসন্ধানী সাংবাদিক')], max_length=60, verbose_name='আবেদনের পদ')),
                ('district', models.CharField(max_length=100, verbose_name='জেলা / এলাকা')),
                ('education', models.CharField(max_length=200, verbose_name='শিক্ষাগত যোগ্যতা')),
                ('experience', models.TextField(blank=True, verbose_name='পূর্ব অভিজ্ঞতা')),
                ('motivation', models.TextField(verbose_name='আবেদনের কারণ')),
                ('portfolio', models.URLField(blank=True, verbose_name='পোর্টফোলিও লিংক')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/%Y/%m/', verbose_name='জীবনবৃত্তান্ত (CV)')),
                ('status', models.CharField(choices=[('pending', 'মুলতুবি'), ('reviewed', 'পর্যালোচিত'), ('shortlisted', 'শর্টলিস্টেড'), ('selected', 'নির্বাচিত'), ('rejected', 'বাতিল')], default='pending', max_length=20, verbose_name='অবস্থা')),
                ('notes', models.TextField(blank=True, verbose_name='অভ্যন্তরীণ নোট')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='তারিখ')),
            ],
            options={
                'verbose_name': 'প্রতিনিধি আবেদন',
                'verbose_name_plural': 'প্রতিনিধি আবেদনসমূহ',
                'ordering': ['-created'],
            },
        ),
    ]
