# Generated by Django 6.0.4 on 2026-04-22 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adrequest_contactmessage_representativeapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='শিরোনাম')),
                ('description', models.TextField(blank=True, null=True, verbose_name='বিবরণ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/images/%Y/%m/', verbose_name='ছবি')),
                ('video', models.FileField(blank=True, null=True, upload_to='ads/videos/%Y/%m/', verbose_name='ভিডিও')),
                ('ad_redirect_url', models.URLField(blank=True, null=True, verbose_name='রিডাইরেক্ট URL')),
                ('placement', models.CharField(choices=[('inline', 'ইনলাইন (নিউজফিডের মাঝে)'), ('banner', 'ব্যানার (হেডার/ফুটার)'), ('sidebar', 'সাইডবার')], default='inline', max_length=20, verbose_name='স্থান')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('show_every', models.PositiveIntegerField(default=7, help_text='৫–২০ এর মধ্যে একটি সংখ্যা দিন', verbose_name='প্রতি কত পোস্টে দেখাবে')),
                ('priority', models.PositiveIntegerField(default=0, help_text='বেশি সংখ্যা = বেশি অগ্রাধিকার', verbose_name='অগ্রাধিকার')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='তৈরি')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='মেয়াদ শেষ')),
            ],
            options={
                'verbose_name': 'বিজ্ঞাপন',
                'verbose_name_plural': 'বিজ্ঞাপনসমূহ',
                'ordering': ['-priority', '-created'],
            },
        ),
    ]
