# Generated by Django 6.0.4 on 2026-04-21 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='accounts/photos/', verbose_name='Profile Photo')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('bio', models.TextField(blank=True, help_text='Shown on bylines and the reporter profile page.', max_length=600, verbose_name='Short Bio')),
                ('designation', models.CharField(blank=True, help_text='e.g. Senior Reporter, Photo Editor', max_length=120, verbose_name='Job Title / Designation')),
                ('department', models.CharField(blank=True, help_text='e.g. National Desk, Sports, Features', max_length=120, verbose_name='Department')),
                ('twitter_handle', models.CharField(blank=True, max_length=80, verbose_name='Twitter / X Handle')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook Profile URL')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn Profile URL')),
                ('personal_email', models.EmailField(blank=True, max_length=254, verbose_name='Personal / Alternate Email')),
                ('is_reporter', models.BooleanField(default=False, help_text='Can create and edit their own posts.', verbose_name='Is Reporter')),
                ('is_editor', models.BooleanField(default=False, help_text='Can publish, unpublish, and edit any post.', verbose_name='Is Editor')),
                ('is_photographer', models.BooleanField(default=False, help_text='Primarily uploads photos and captions.', verbose_name='Is Photographer')),
                ('is_columnist', models.BooleanField(default=False, help_text='Writes opinion / column pieces.', verbose_name='Is Columnist')),
                ('is_admin', models.BooleanField(default=False, help_text='Full administrative access (mirrors Django staff).', verbose_name='Is Admin')),
                ('is_active_staff', models.BooleanField(default=True, help_text='Uncheck to disable without deleting the account.', verbose_name='Active Staff')),
                ('employee_id', models.CharField(blank=True, max_length=40, verbose_name='Employee ID')),
                ('joining_date', models.DateField(blank=True, null=True, verbose_name='Date of Joining')),
                ('credits', models.IntegerField(default=0, help_text='Earned automatically: +50 when a post is first published, -50 if a published post is deleted within 60 days of publication. Cannot go below 0.', verbose_name='Credits')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
